app = "conecta-sign"
org = "Conecta"
primary_region = "lax"

[build]
  dockerfile = "docker/Dockerfile"

[env]
  PORT = "8080"
  HOSTNAME = "0.0.0.0"
  NODE_ENV = "production"
  NEXTAUTH_URL = "https://sign.holaconecta.com"
  NEXTAUTH_URL_INTERNAL = "https://sign.holaconecta.com"
  NEXT_PUBLIC_WEBAPP_URL = "https://sign.holaconecta.com"
  NEXT_PRIVATE_INTERNAL_WEBAPP_URL = "https://sign.holaconecta.com"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [[http_service.checks]]
    interval = "30s"
    timeout = "10s"
    grace_period = "120s"
    method = "GET"
    path = "/api/health"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 2048

[[metrics]]
  port = 9091
  path = "/metrics"